server:
  port: 8092
spring:
  application:
    name: calificacion-service
eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"